In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
f(x) = W*X + k

已知的数据
X {x1,x2,x3}  y


W {a,b,c}
3x + 4y + 5z = 6
2x + 3y + 6z = 9

# 把X,y带入公式，得到如下关系
# 样本数量少于样本特征，就会构成不满秩矩阵
# 机器学习中，此种模型用线性函数来训练不会出错，但是准确率低
a*3 + b*4 + c*5 = 6
a*2 + b*3 + c*6 = 9


无解的矩阵

3  4  5
2  4  6


3  4
2  5
3  2

SyntaxError: invalid syntax (<ipython-input-17-c99942079b8c>, line 4)

In [ ]:
# a / b  ----  a  *  1/b

# A / B  ----  A *  E/B

# 1 0
# 0 1

a = np.array([1,2],[3,4])
# a*b = E
1 2   a b   1 0 
3 4   c d   0 1

a + 2c = 1
b + 2d = 0
3a+ 4c = 0
3b +4d = 1


# 单位矩阵
1 0 0
0 1 0
0 0 1

# 不满秩矩阵，引入单位矩阵，就构成了满秩
# 岭回归会把无效系数无限向0压缩
3  4  5     1 0 0     3+λ  4   5
2  4  6 +λ*0 1 0  =  2  4+λ   6   ==== 求解
            0 0 1     0     0   λ

In [16]:
a = np.array([[1,2],[3,4],[2,7]])
# 不满秩无法求逆
np.linalg.inv(a)
# np.linalg.matrix_rank(a)

LinAlgError: Last 2 dimensions of the array must be square

In [6]:
# 不满秩矩阵
n = np.array([[3,4,1],[2,4,6],[1,2,3]])

np.linalg.matrix_rank(n)

2

In [8]:
n

array([[3, 4, 1],
       [2, 4, 6],
       [1, 2, 3]])

In [7]:
# 转秩矩阵的求法
n.T

array([[3, 2, 1],
       [4, 4, 2],
       [1, 6, 3]])

In [2]:
X = np.array([[1,2,3,4],[3,5,7,9]])
y = np.array([1,3])

In [3]:
from sklearn.linear_model import LinearRegression,Ridge

In [4]:
linear = LinearRegression()
linear.fit(X,y)
linear.coef_

array([-0.18620678,  0.13191209,  0.17588279,  0.25462923])

In [5]:
# 惩罚项
# 越大，系数压缩越严重，原始系数对结果影响变小
# 越小，系数压缩越轻，原始系数对结果影响大
# 如果为0,则岭回归就变成了线性回归模型
ridge = Ridge(alpha=0.001)
ridge.fit(X,y)
ridge.coef_

array([0.07407133, 0.111107  , 0.14814266, 0.18517833])

In [ ]:
w1  -100  400  10000

w2  1   2   3

10  5  6
9   4  7

In [31]:
1*10 + 2*5 + 3*6

38

In [32]:
1*9 + 2*4 + 3*7

38

In [28]:
-100*10 + 400*5 + 10000*6

61000

In [30]:
-100*9  + 400*4 + 10000*7

70700