In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [32]:
lenses = pd.read_csv('lenses.txt',sep='\t',header=None)
train = lenses.values[:,:4]
target = lenses.values[:,4]

In [14]:
train.shape

(24, 4)

In [16]:
target

array(['no lenses', 'soft', 'no lenses', 'hard', 'no lenses', 'soft',
       'no lenses', 'hard', 'no lenses', 'soft', 'no lenses', 'hard',
       'no lenses', 'soft', 'no lenses', 'no lenses', 'no lenses',
       'no lenses', 'no lenses', 'hard', 'no lenses', 'soft', 'no lenses',
       'no lenses'], dtype=object)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.model_selection import train_test_split

In [33]:
# 特征之间存在关联性     很高 高 中 矮 很矮  100 10 5 1 0
# 特征之间不存在关联性   黑 白  1 0  0 1
# OneHotEncoder

map_dic = {
    'pre':0,
    'young':1,
    'presbyopic':2,
    'hyper':0,
    'myope':1,
    'reduced':1,
    'normal':0
}
train[:,0] = Series(train[:,0]).map(map_dic)
train[:,1] = Series(train[:,1]).map(map_dic)
train[:,3] = Series(train[:,3]).map(map_dic)

In [60]:
train

array([[1, 1, 'no', 1],
       [1, 1, 'no', 0],
       [1, 1, 'yes', 1],
       [1, 1, 'yes', 0],
       [1, 0, 'no', 1],
       [1, 0, 'no', 0],
       [1, 0, 'yes', 1],
       [1, 0, 'yes', 0],
       [0, 1, 'no', 1],
       [0, 1, 'no', 0],
       [0, 1, 'yes', 1],
       [0, 1, 'yes', 0],
       [0, 0, 'no', 1],
       [0, 0, 'no', 0],
       [0, 0, 'yes', 1],
       [0, 0, 'yes', 0],
       [2, 1, 'no', 1],
       [2, 1, 'no', 0],
       [2, 1, 'yes', 1],
       [2, 1, 'yes', 0],
       [2, 0, 'no', 1],
       [2, 0, 'no', 0],
       [2, 0, 'yes', 1],
       [2, 0, 'yes', 0]], dtype=object)

In [35]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [57]:
n = np.array(['a','b','a','a','b','c','c','d'])
label_1 = LabelEncoder()

n1 = label_1.fit_transform(n)
display(n1)
# 0   1 0 0 0
# 1   0 1 0 0
# 2   0 0 1 0 
# 3   0 0 0 1

onehot_1 = OneHotEncoder()
onehot_1.fit_transform(n1.reshape(-1,1)).todense()

array([0, 1, 0, 0, 1, 2, 2, 3], dtype=int32)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [42]:
label_enc = LabelEncoder()
label_data = label_enc.fit_transform(train[:,2])

oneHot_enc = OneHotEncoder()
train2 = oneHot_enc.fit_transform(label_data.reshape(-1,1)).todense()

In [62]:
train2

matrix([[1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.]])

In [48]:
train[:,0].reshape(-1,1)
train2

matrix([[1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.]])

In [65]:
train[:,0].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [66]:
train2

matrix([[1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.]])

In [49]:
good_train = np.hstack((train[:,0].reshape(-1,1),train[:,1].reshape(-1,1),train[:,3].reshape(-1,1),train2))
good_train

matrix([[1, 1, 1, 1.0, 0.0],
        [1, 1, 0, 1.0, 0.0],
        [1, 1, 1, 0.0, 1.0],
        [1, 1, 0, 0.0, 1.0],
        [1, 0, 1, 1.0, 0.0],
        [1, 0, 0, 1.0, 0.0],
        [1, 0, 1, 0.0, 1.0],
        [1, 0, 0, 0.0, 1.0],
        [0, 1, 1, 1.0, 0.0],
        [0, 1, 0, 1.0, 0.0],
        [0, 1, 1, 0.0, 1.0],
        [0, 1, 0, 0.0, 1.0],
        [0, 0, 1, 1.0, 0.0],
        [0, 0, 0, 1.0, 0.0],
        [0, 0, 1, 0.0, 1.0],
        [0, 0, 0, 0.0, 1.0],
        [2, 1, 1, 1.0, 0.0],
        [2, 1, 0, 1.0, 0.0],
        [2, 1, 1, 0.0, 1.0],
        [2, 1, 0, 0.0, 1.0],
        [2, 0, 1, 1.0, 0.0],
        [2, 0, 0, 1.0, 0.0],
        [2, 0, 1, 0.0, 1.0],
        [2, 0, 0, 0.0, 1.0]], dtype=object)

In [50]:
target

array(['no lenses', 'soft', 'no lenses', 'hard', 'no lenses', 'soft',
       'no lenses', 'hard', 'no lenses', 'soft', 'no lenses', 'hard',
       'no lenses', 'soft', 'no lenses', 'no lenses', 'no lenses',
       'no lenses', 'no lenses', 'hard', 'no lenses', 'soft', 'no lenses',
       'no lenses'], dtype=object)

In [67]:
X_train,X_test,y_train,y_test = train_test_split(good_train,target,test_size=0.2)

In [72]:
def show_train_test_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    train_score = model.score(X_train,y_train)
    test_score = model.score(X_test,y_test)
    # 获取对象名字
    model_name = model.__class__.__name__
    
    print("{}训练集评分是{} 测试集评分是{}".format(model_name,train_score,test_score))

In [76]:
knn = KNeighborsClassifier(n_neighbors=1)
show_train_test_score(knn,X_train,X_test,y_train,y_test)

KNeighborsClassifier训练集评分是1.0 测试集评分是0.6


In [94]:
X_train.shape

(19, 5)

In [95]:
X_test.shape

(5, 5)

In [93]:
logistic = LogisticRegression(C=0.1)
show_train_test_score(logistic,X_train,X_test,y_train,y_test)

LogisticRegression训练集评分是0.5789473684210527 测试集评分是0.8


In [101]:
tree = DecisionTreeClassifier(max_depth=3)
show_train_test_score(tree,X_train,X_test,y_train,y_test)

DecisionTreeClassifier训练集评分是0.8947368421052632 测试集评分是0.8


In [102]:
gnb = GaussianNB()
show_train_test_score(gnb,X_train,X_test,y_train,y_test)

GaussianNB训练集评分是0.8947368421052632 测试集评分是0.8


In [103]:
mnb = MultinomialNB()
show_train_test_score(mnb,X_train,X_test,y_train,y_test)

MultinomialNB训练集评分是0.8421052631578947 测试集评分是0.8


In [104]:
bnb = BernoulliNB()
show_train_test_score(bnb,X_train,X_test,y_train,y_test)

BernoulliNB训练集评分是0.8947368421052632 测试集评分是0.8
